name: CI Gate
on:
  pull_request:
    branches: [ "main", "develop" ]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4 # Setup .npmrc file to publish to npm
        with:
          node-version: '20.x'
          cache: 'yarn'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command
      - name: Run CI
        uses: borales/actions-yarn@v4
        with:
          cmd: ci # will run `yarn ci` command